### PR TITLE
Made encoding and autojunk explicit as kwargs on init

### PR DESCRIPTION
**Pull request by IYIagnus**
If not specifed, the class will default to previous defaults. Small but quite useful update. Default encoding settings for open() can cause trouble for some files. Autojunk seems to make a huge difference in run time for large files (as in hours down to minutes).

### CODE REVIEW

**Comment by IYIagnus** [comment]
Is Travis CI intentionally testing with python 2.7? Should I maintain backwards compatibility?

 - Magnus

**Comment by anastasia** [comment]
Excellent!!

Sorry for the delay. Looks great — merging now. Will need to fix some tests. Backward compatibility is unnecessary at this point, I think. I'll update that too.

**Comment by IYIagnus** [comment]
Oh wow, thanks - I actually expected I'd have to fix the tests myself! I just continued with the broken ones for a while since I didn't hear from you on the first comments.

**Comment by anastasia** [comment]
I just need to make another release sometime soon, ack!

**Pull request merged**
